export const ITEM_ERRORS = {
  REQUIRED_FIELDS: '사진과 필수 정보를 입력해주세요.',
  TITLE_REQUIRED: '제목을 입력해주세요.',
  TITLE_TOO_LONG: (max: number) => `제목은 ${max}자 이내로 입력해주세요.`,
  CONTENT_REQUIRED: '내용을 입력해주세요.',
  CONTENT_TOO_LONG: (max: number) =>
    `내용은 ${max.toLocaleString('ko-KR')}자 이내로 입력해주세요.`,
  STATE_REQUIRED: '거래 상태를 선택해주세요.',
  QUANTITY_REQUIRED: '수량을 입력해주세요.',
  QUANTITY_TOO_LOW: '수량은 1개 이상이어야 합니다.',
  QUANTITY_TOO_HIGH: '수량은 99개 이하여야 합니다.',
  QUANTITY_NOT_INTEGER: '수량은 정수로 입력해주세요.',
  GROUP_REQUIRED: '최소 한 개의 그룹을 선택해주세요.',
  IMAGE_REJECTED: '등록할 수 없는 이미지입니다.',
  REMOVE_IMAGES_FIRST: '사진을 모두 삭제한 뒤 다시 선택해주세요.',
  ANALYSIS_FIELDS_MISSING: 'AI 분석 결과에 제목이나 내용이 없습니다.',
  IMAGE_ANALYSIS_FAILED: '이미지 분석에 실패했습니다. 다시 시도해주세요.',
  IMAGE_TYPE_UNSUPPORTED: 'JPEG, PNG, WebP 이미지만 선택할 수 있습니다.',
  IMAGE_TOO_LARGE: '사진 한 장의 크기는 최대 10MB입니다.',
  IMAGE_COUNT_EXCEEDED: '사진은 최대 3장까지 등록할 수 있습니다.',
  IMAGE_READ_FAILED: '사진을 읽을 수 없습니다. 다시 선택해주세요.',
  IMAGE_COUNT_INVALID: '이미지는 1장 이상 3장 이하로 선택해야 합니다.',
  EXISTING_IMAGE_UPLOAD_UNSUPPORTED:
    '기존 사진은 이미지 ID를 사용하는 수정 API로 처리해야 합니다.',
  UPLOAD_URL_COUNT_MISMATCH: '발급된 업로드 URL 개수가 이미지 개수와 다릅니다.',
  CONTENT_REJECTED: '등록할 수 없는 내용입니다.',
  MODERATION_ID_MISSING: '검수 ID가 반환되지 않았습니다.',
  REGISTER_FAILED: '물품 등록에 실패했습니다. 다시 시도해주세요.',
  NOT_FOUND: '물품을 찾을 수 없습니다.',
  DETAIL_LOAD_FAILED: '물품 정보를 불러오지 못했습니다.\n잠시 후 다시 시도해주세요.',
  EDIT_LOAD_FAILED: '물품 정보를 불러오지 못했습니다. 다시 시도해주세요.',
  DELETE_NOT_FOUND: '삭제할 물품을 찾을 수 없습니다.',
  DELETE_FAILED: '물품 삭제에 실패했습니다. 다시 시도해주세요.',
  NEW_IMAGE_ON_EDIT_UNSUPPORTED:
    '현재 수정 API에서는 새 이미지 추가를 지원하지 않습니다.',
  UPDATE_FAILED: '물품 수정에 실패했습니다. 다시 시도해주세요.',
} as const
